# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/admin/Desktop/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/admin/Desktop/project_1/project_1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/admin/Desktop/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/admin/Desktop/project_1/arm/build.coe
add_files c:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/sdr/matlab_filter_coe/hilbert_16bit_162order_wpass001_099.coe
read_verilog -library xil_defaultlib {
  C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/sdr/AM/AM_sfix16.v
  C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/sdr/FM/FM_fix16.v
  C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/sdr/Clock/Freq_div.v
  C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/sdr/IQ/IQ_synth_fix16.v
  C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/sdr/PWM.v
  C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/armv4core/adder32.v
  C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/armv4core/def.v
  C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/armv4core/alu.v
  C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/armv4core/armv4core.v
  C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/debug/bram_debug.v
  C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/new/bridge.v
  C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/new/bus.v
  C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/armv4core/cpsr.v
  C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/sdr/differential_code/diff_code_gen.v
  C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/armv4core/ex_stage.v
  C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/armv4core/ex_wb.v
  C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/armv4core/forward_ctrl.v
  C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/armv4core/hazard_ctrl.v
  C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/armv4core/id_ex.v
  C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/armv4core/id_stage.v
  C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/armv4core/if_id.v
  C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/armv4core/irq_ctrl.v
  C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/debug/jtag2bram.v
  C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/armv4core/ldm_ctrl.v
  C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/armv4core/memctrl.v
  C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/armv4core/mul_ctrl.v
  C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/armv4core/multiplier32.v
  C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/sdr/my_SDR_v11.v
  C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/armv4core/one_detector.v
  C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/armv4core/pc.v
  C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/armv4core/registers.v
  C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/armv4core/shift.v
  C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/armv4core/shift_unit.v
  C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/sdr/Signma_Delta_PDM/sigma_delta_modulator.v
  C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/armv4core/swp_ctrl.v
  C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/uart_soc/uart.v
  C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/uart_soc/uart_ctrl.v
  C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/uart_soc/uart_fifo.v
  C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/uart_soc/uart_intf.v
  C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/armv4core/wb_stage.v
  C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/new/top.v
}
read_ip -quiet C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/ip/axi_bram_ctrl_0/axi_bram_ctrl_0.xci
set_property used_in_implementation false [get_files -all c:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/ip/axi_bram_ctrl_0/axi_bram_ctrl_0_ooc.xdc]

read_ip -quiet C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/ip/jtag_axi_0/jtag_axi_0.xci
set_property used_in_implementation false [get_files -all c:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/ip/jtag_axi_0/constraints/jtag_axi.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/ip/jtag_axi_0/constraints/jtag_axi_0_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/ip/jtag_axi_0/constraints/jtag_axi_0_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/ip/jtag_axi_0/jtag_axi_0_ooc.xdc]

read_ip -quiet C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/ip/xbip_multadd_1/xbip_multadd_1.xci
set_property used_in_implementation false [get_files -all c:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/ip/xbip_multadd_1/xbip_multadd_1_ooc.xdc]

read_ip -quiet C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/ip/vio_0/vio_0.xci
set_property used_in_implementation false [get_files -all c:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/ip/vio_0/vio_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/ip/vio_0/vio_0_ooc.xdc]

read_ip -quiet C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/ip/bram_0/bram_0.xci
set_property used_in_implementation false [get_files -all c:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/ip/bram_0/bram_0_ooc.xdc]

read_ip -quiet C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/ip/xbip_multadd_0/xbip_multadd_0.xci
set_property used_in_implementation false [get_files -all c:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/ip/xbip_multadd_0/xbip_multadd_0_ooc.xdc]

read_ip -quiet c:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xci
set_property used_in_implementation false [get_files -all c:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_ooc.xdc]

read_ip -quiet c:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/ip/oddr_0/oddr_0.xci

read_ip -quiet c:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/ip/adder_sfix32/adder_sfix32.xci
set_property used_in_implementation false [get_files -all c:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/ip/adder_sfix32/adder_sfix32_ooc.xdc]

read_ip -quiet c:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/ip/cic_interp_rate4000_1/cic_interp_rate4000_1.xci
set_property used_in_implementation false [get_files -all c:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/ip/cic_interp_rate4000_1/cic_interp_rate4000_1_ooc.xdc]

read_ip -quiet c:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/ip/dds_sfix16/dds_sfix16.xci
set_property used_in_implementation false [get_files -all c:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/ip/dds_sfix16/dds_sfix16_ooc.xdc]

read_ip -quiet c:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/ip/fir_compiler_0/fir_compiler_0.xci
set_property used_in_implementation false [get_files -all c:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/ip/fir_compiler_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all c:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/ip/fir_compiler_0/fir_compiler_0_ooc.xdc]

read_ip -quiet c:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/ip/mult_sfix16/mult_sfix16.xci
set_property used_in_implementation false [get_files -all c:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/ip/mult_sfix16/mult_sfix16_ooc.xdc]

read_ip -quiet c:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/ip/xbip_multadd_2/xbip_multadd_2.xci
set_property used_in_implementation false [get_files -all c:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/ip/xbip_multadd_2/xbip_multadd_2_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/admin/Desktop/project_1/project_1.srcs/constrs_1/new/top.xdc
set_property used_in_implementation false [get_files C:/Users/admin/Desktop/project_1/project_1.srcs/constrs_1/new/top.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7a100tfgg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
