# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/ip/jtag_axi_0/jtag_axi_0.xci
# IP: The module: 'jtag_axi_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/ip/jtag_axi_0/constraints/jtag_axi.xdc
# XDC: The top module name and the constraint reference have the same name: 'jtag_axi_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/ip/jtag_axi_0/jtag_axi_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'jtag_axi_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/ip/jtag_axi_0/jtag_axi_0.xci
# IP: The module: 'jtag_axi_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/ip/jtag_axi_0/constraints/jtag_axi.xdc
# XDC: The top module name and the constraint reference have the same name: 'jtag_axi_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/ip/jtag_axi_0/jtag_axi_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'jtag_axi_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
