# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/ip/xbip_multadd_2/xbip_multadd_2.xci
# IP: The module: 'xbip_multadd_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/ip/xbip_multadd_2/xbip_multadd_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xbip_multadd_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/ip/xbip_multadd_2/xbip_multadd_2.xci
# IP: The module: 'xbip_multadd_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/ip/xbip_multadd_2/xbip_multadd_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xbip_multadd_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
