# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/ip/xbip_multadd_1/xbip_multadd_1.xci
# IP: The module: 'xbip_multadd_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/ip/xbip_multadd_1/xbip_multadd_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xbip_multadd_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/ip/xbip_multadd_1/xbip_multadd_1.xci
# IP: The module: 'xbip_multadd_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/ip/xbip_multadd_1/xbip_multadd_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xbip_multadd_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
