# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/admin/Desktop/project_1/.Xil/Vivado-18244-DESKTOP-494Q00J/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7z020clg484-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include c:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/ip/jtag_axi_0/hdl/verilog {
      D:/Software/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      D:/Software/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include c:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/ip/jtag_axi_0/hdl/verilog {
      C:/Users/admin/Desktop/project_1/.Xil/Vivado-18244-DESKTOP-494Q00J/realtime/axi_bram_ctrl_0_stub.v
      C:/Users/admin/Desktop/project_1/.Xil/Vivado-18244-DESKTOP-494Q00J/realtime/jtag_axi_0_stub.v
      C:/Users/admin/Desktop/project_1/.Xil/Vivado-18244-DESKTOP-494Q00J/realtime/bram_0_stub.v
      C:/Users/admin/Desktop/project_1/.Xil/Vivado-18244-DESKTOP-494Q00J/realtime/vio_0_stub.v
      C:/Users/admin/Desktop/project_1/.Xil/Vivado-18244-DESKTOP-494Q00J/realtime/xbip_multadd_0_stub.v
      C:/Users/admin/Desktop/project_1/.Xil/Vivado-18244-DESKTOP-494Q00J/realtime/xbip_multadd_1_stub.v
      C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/armv4core/adder32.v
      C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/armv4core/def.v
      C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/armv4core/alu.v
      C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/armv4core/armv4core.v
      C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/debug/bram_debug.v
      C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/new/bridge.v
      C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/new/bus.v
      C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/armv4core/cpsr.v
      C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/armv4core/ex_stage.v
      C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/armv4core/ex_wb.v
      C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/armv4core/forward_ctrl.v
      C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/armv4core/hazard_ctrl.v
      C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/armv4core/id_ex.v
      C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/armv4core/id_stage.v
      C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/armv4core/if_id.v
      C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/armv4core/irq_ctrl.v
      C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/debug/jtag2bram.v
      C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/armv4core/ldm_ctrl.v
      C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/armv4core/memctrl.v
      C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/armv4core/mul_ctrl.v
      C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/armv4core/multiplier32.v
      C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/armv4core/one_detector.v
      C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/armv4core/pc.v
      C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/armv4core/registers.v
      C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/armv4core/shift.v
      C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/armv4core/shift_unit.v
      C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/armv4core/swp_ctrl.v
      C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/uart_soc/uart.v
      C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/uart_soc/uart_ctrl.v
      C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/uart_soc/uart_fifo.v
      C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/uart_soc/uart_intf.v
      C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/armv4core/wb_stage.v
      C:/Users/admin/Desktop/project_1/project_1.srcs/sources_1/new/top.v
    }
      rt::read_vhdl -lib xpm D:/Software/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top top
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "C:/Users/admin/Desktop/project_1/.Xil/Vivado-18244-DESKTOP-494Q00J/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
